In [1]:
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [3]:
df = pd.read_csv("data_capec_multilabel.csv")

C:\Users\ACER\AppData\Local\Temp\ipykernel_13324\2674094088.py:1: DtypeWarning: Columns (9,11,12,13,14,15,16,18,19) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("data_capec_multilabel.csv")

In [4]:
df.head()

,timestamp,src_ip,src_port,dst_ip,dst_port,request_http_method,request_http_request,request_http_protocol,request_user_agent,request_referer,...,126 - Path Traversal,66 - SQL Injection,16 - Dictionary-based Password Attack,310 - Scanning for Vulnerable Software,153 - Input Data Manipulation,248 - Command Injection,274 - HTTP Verb Tampering,194 - Fake the Source of Data,34 - HTTP Response Splitting,33 - HTTP Request Smuggling
0,17/Jul/2020:12:23:34 +0100,172.26.0.1,55894.0,172.26.0.4,80.0,GET,/,HTTP/1.1,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3...,NaN,...,0,0,0,0,0,0,0,0,0,0
1,17/Jul/2020:12:23:41 +0100,172.26.0.1,55897.0,172.26.0.4,80.0,GET,/blog/index.php/2020/04/04/voluptatum-reprehen...,HTTP/1.1,Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; r...,NaN,...,0,0,0,0,0,0,0,0,0,0
2,17/Jul/2020:12:23:51 +0100,172.26.0.1,55901.0,172.26.0.4,80.0,GET,/blog/xmlrpc.php?rsd,HTTP/1.1,Mozilla/4.0 (compatible; MSIE 6.0; Windows NT ...,NaN,...,0,0,0,0,0,0,0,0,0,0
3,17/Jul/2020:12:23:51 +0100,172.26.0.1,55902.0,172.26.0.4,80.0,GET,/,HTTP/1.1,Mozilla/5.0 (Linux; Android 4.2.2; SM-T110 Bui...,NaN,...,0,0,0,0,0,0,0,0,0,0
4,17/Jul/2020:12:23:58 +0100,172.26.0.1,55903.0,172.26.0.4,80.0,GET,/blog/index.php/2020/04/04/nihil-tenetur-et-ad...,HTTP/1.1,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2...,NaN,...,0,0,0,0,0,0,0,0,0,0

In [5]:
df.describe()

,src_port,dst_port,request_do_not_track,response_http_status_code,response_content_length,000 - Normal,272 - Protocol Manipulation,242 - Code Injection,88 - OS Command Injection,126 - Path Traversal,66 - SQL Injection,16 - Dictionary-based Password Attack,310 - Scanning for Vulnerable Software,153 - Input Data Manipulation,248 - Command Injection,274 - HTTP Verb Tampering,194 - Fake the Source of Data,34 - HTTP Response Splitting,33 - HTTP Request Smuggling
count,907813.000000,907813.0,705.0,907813.000000,904523.000000,907815.000000,907815.000000,907815.000000,907815.000000,907815.000000,907815.000000,907815.000000,907815.000000,907815.000000,907815.000000,907815.000000,907815.000000,907815.000000,907815.000000
mean,56749.866303,80.0,1.0,302.851342,17999.002713,0.578526,0.010082,0.017434,0.008242,0.023124,0.275729,0.002035,0.002994,0.002503,0.000001,0.005989,0.061846,0.021742,0.001167
std,5331.665110,0.0,0.0,100.599167,20200.194933,0.493795,0.099904,0.130883,0.090409,0.150296,0.446881,0.045060,0.054636,0.049965,0.001050,0.077157,0.240876,0.145841,0.034135
min,1407.000000,80.0,1.0,200.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,51992.000000,80.0,1.0,200.000000,276.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,55747.000000,80.0,1.0,301.000000,21080.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,62110.000000,80.0,1.0,404.000000,25174.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,65534.000000,80.0,1.0,501.000000,236440.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000